# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/AnswerDotAI/nbdev
    rev: 2.3.34
    hooks:
      - id: nbdev_clean
        entry: nbdev_clean --fname
        pass_filenames: true
        files: '.*\.ipynb$'
